services:
  google-calendar:
    build: .
    container_name: google-calendar
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    ports:
      - 8011:80
    volumes:
      - .:/app